### ISSUE TITLE
Copy/paste and disable breaks the combinator.

### ISSUE THREAD

**Issue by mig5323** [Sharparam/cybersyn-combinator#47]
### Description

In certain circumstances, you can have a CS combinator with output, but no output signals in the grid.

### Expected behaviour

Signals should not disappear from the combinator GUI.

### Steps to reproduce

1. Set a combinator with some signal in the Output Signals, then disable it.
2. Copy the combinator.
3. Clear the combinator, then paste back over it.
4. Enable the combinator, and you'll see a signal output on mousing over the combi with nothing in the Output Signals GUI.

### Mod version

2.3.0

### Factorio version

2.0.21

### Operating system

Windows

**Comment by Sharparam** [comment]
It's really strange that it only happens when it's disabled. It seems though that copy-pasting onto the same entity is something that should just be disabled altogether, because the base game seems to do that.

**Comment by Sharparam** [comment]
Should now be fixed in v2.3.1.

**Comment by mig5323** [comment]
If you paste the ghost first, then copy that...it isn't the same unit, and breaks again in 2.3.1. Sorry.

**Comment by Sharparam** [comment]
Ah I see that there were a couple of commits in my other branch fixing some ghost-related oddities that were not in main branch.

I've pulled those fixes into main branch and made a new release v2.3.2 that includes those, please try that version and see if all the issues are fixed now!

**Comment by mig5323** [comment]
Unfortunately, the ghost paste still breaks things.

**Comment by Sharparam** [comment]
Do you have some reproduction steps for the ghost case?

**Comment by mig5323** [comment]
I build a combi as normal, set a signal, and disable it. Copy that and paste a ghost of it somewhere. Clear the original combi, and copy the ghost and paste that over the top.

**Comment by Sharparam** [comment]
Ok I think I've located that issue now, there are some checks in the paste code that only check for source and destination being non-ghosts. I've added new checks there so it should work properly with ghosts now. When I try your reproduction steps after my fix it now works as it should.

I've published v2.3.3 with these fixes, please try that and see if it all works now!

**Comment by mig5323** [comment]
Still broken. :(
Here's a save game, in case that's helpful.
[CSCombiTest.zip](https://github.com/user-attachments/files/17972500/CSCombiTest.zip)

**Comment by Sharparam** [comment]
What are the new reproduction steps?

**Comment by mig5323** [comment]
I double checked this morning, and verified I'm on 2.3.3. If I do the copy a disabled combi to a ghost, then paste that ghost over another combi, I get the output with no signals visible. I also found this morning that if you copy an active combi, then disable the ghost, that also has the same behavior when pasting onto a built combi. Pasting a disabled ghost over another ghost then building that ghost works appropriately.

**Comment by Sharparam** [comment]
> If I do the copy a disabled combi to a ghost, then paste that ghost over another combi, I get the output with no signals visible.

I managed to reproduce this and have a fix for it.

> I also found this morning that if you copy an active combi, then disable the ghost, that also has the same behavior when pasting onto a built combi.

I wasn't able to reproduce this case though, maybe I'm misunderstanding the steps?

I have v2.3.4 ready to be tested, I figure that instead of pushing it out to the mod portal to maybe have to be replaced yet again with a new version, maybe you can download it directly from the builds and test first? Especially the second case that I wasn't able to reproduce on my own.

Artifact download is on this link: https://github.com/Sharparam/cybersyn-combinator/actions/runs/12127085945/artifacts/2263649488

Inside `mod.zip` is the actual mod zip (`cybersyn-combinator_2.3.4.zip`) that you need to place in your mods directory.

**Comment by mig5323** [comment]
I just tried pasting a disabled combi over another already built combi, and had the vanishing signal. Copy/paste from ghost to built combi still broken too on 2.3.4.
I hadn't tried this before, but copy/pasting a non-disabled to built or ghost also vanishes the signal. Right click/left click copy works fine.
Sorry for breaking this in such an "interesting" way. :)

**Comment by Sharparam** [comment]
Oh I think I see it now. I was misunderstanding when you said copy/paste.

When copy-pasting with Ctrl+C and Ctrl+V, there does indeed seem to be an issue that the mod can't detect that action and perform the signal sort, so there ends up being "hidden" sections planted in the combinator.

There doesn't seem to be any events for this generated in the game, so not sure how to deal with that.

I'm considering maybe it's better to just release the current state of the logistic section support branch, since this will actually solve this and some other jank that revolves around the special handling of signals after 2.0.

I made a new update to that branch and you can download the zip like with the previous link here: https://github.com/Sharparam/cybersyn-combinator/actions/runs/12130072284/artifacts/2264547663 (with the actual mod zip inside that zip).

(It has the same v2.3.4 version.)

I have tested it a little for a while now and I haven't noticed any big issues, there's just a few APIs missing from Factorio's side to make it fully feature-complete. But it should make the Ctrl+C and Ctrl+V copy-pasting work properly. It would be great if you can test it a little so it's not just tested by me!

**Comment by Sharparam** [comment]
I've also posted [a modding interface request](https://forums.factorio.com/viewtopic.php?f=28&t=123592) for the missing event. Though if the current version of the logistic section support is good enough, I can release that to solve the issue that way instead.

**Comment by mig5323** [comment]
Well, the signals don't disappear with the revised 2.3.4. Yay! However, there's some weirdness with empty logistic groups showing up. I got two extra empty logistic groups showing up on each paste event. The below screenshot is after a copy to ghost then copy to an actual combi.
![image](https://github.com/user-attachments/assets/d84ca665-50b6-4ebb-8697-74dd35d97d8d)

**Comment by mig5323** [comment]
With those caveats, I'll call it good enough. It'd be nice if they'd fix that event though. :)

**Comment by Sharparam** [comment]
I actually think I managed to improve the logic a bit for when there's a bunch of empty sections after pasting. It's probably not completely perfect but better than before at least.

There's a new version of the WIP branch here: https://github.com/Sharparam/cybersyn-combinator/actions/runs/12148934519/artifacts/2270161726
(Same version and procedure for installing as before)

It will now try to do a better job to find suitable available sections when a combinator has been pasted.

@mig5323 Can you try this version and see if it behaves better? In my testing it does a pretty good job now. As long as any empty sections used for network or Cybersyn signals are not given names (groups). Then I default to just putting them in the item section out of caution. But regular un-grouped sections should now work as expected.

If that all works well, I think it might be ready for a release!

**Comment by mig5323** [comment]
I tested blueprint and mouse copy, both enabled and disabled, and everything seems to work as intended.

**Comment by Sharparam** [comment]
Closing this now since I think all the issues should be resolved.
